### PR TITLE
New build scripting with FLOSS build tools, new manual hints, expanded web font subsets

### PR DESCRIPTION
**Pull request by chrissimpkins**
This PR includes:

- new scripted build approach to reach hinted desktop ttf fonts from UFO source with FLOSS build tools
- new scripted build approach to reach woff web fonts (complete set) from ttf build with FLOSS build tools
- new scripted build approach to reach woff2 web fonts (complete set) from ttf build with FLOSS build tools
- new scripted build approach to reach woff + woff2 web font subsets from subset ttf builds with FLOSS build tools
- adds currency glyphs and general punctuation glyphs to web font subsets (in addition to ASCII + Latin-1 + ~ Latin Ext A)
- new manual instruction set adjustments (ttf control instructions files) for all identified issues in ASCII regular, bold, italic and bold italic sets (EXCEPT zero glyph in regular set... work is currently available in PR #316 to be merged to this branch following review)
- adds FontBakery fstype post compilation fix
- adds FontBakery DSIG table post compilation fix
- Travis CI testing settings modifications to address broken testing builds on Linux platform due to their Trusty upgrade that took place in early September (change defaults to their previous Trusty container for now)
- adds shellcheck shell script CI linting to CI testing
- adds automated ttfautohint install approach that functions on both Linux and OS X platforms (contribution by @lemzwerg)
- adds concurrent linting + build CI testing via new makefile target testing approach (contribution by @mavit)
- adds new build documentation (BUILD.md in docs directory) 
- adds new development ttf, woff, woff2 font builds (`Version 3.000; 2a97b0d-dev`)

Propose merge to `dev` branch which will serve as basis for all upcoming glyph modification work for v3.0 release (and will thereafter remain a stable development branch for reviewed/accepted development work prior to all future releases where release = merge to master branch).  These changes will bring `dev` branch to current status of build tooling that will be necessary to establish a development environment / build / view / test changes to the UFO source code for all future font design changes. 

Please let me know if you have any thoughts/questions/concerns/required changes.

TODO:

- [x] add install paths (and uninstall approach) for all build dependencies to BUILD.md documentation
- [x] build dependency install issue in https://github.com/source-foundry/Hack/pull/309#pullrequestreview-62899027

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@jublo added you as a reviewer as well so that you can see build dependencies and how to establish a development environment for local builds/testing of changes.

@burodepeper @jublo It would be helpful if you could both try to set up a development environment on either a OS X or Linux platform with the contained instructions and let me know if they do not work for you.  We can modify the installations and documentation if this appears to be necessary.  We did a fair amount of work (including modification of Google's woff2 build process in our own fork, work with Werner Lemberg on OS X installs of ttfautohint) to make these build dependency installs as simple and automated as possible.

Big PR with lots of changes. Please let me know if you have any questions or concerns about the work here.

I suggest that we review and approve this before we dive into glyph modifications so that we can base all of our source changes on a `dev` branch that is current with the build tooling.

**Comment by chrissimpkins** [comment]
hmm... new build issue with the Harfbuzz dependency.  Will take a look tomorrow.  Not sure what is going on here.  No changes to build approach there and passed tests yesterday.

Travis line https://travis-ci.org/source-foundry/Hack/jobs/275285829#L1432

**Comment by chrissimpkins** [comment]
Harfbuzz issue is a cURL error on the archive pull https://travis-ci.org/source-foundry/Hack/jobs/275285829#L584

**Comment by chrissimpkins** [comment]
Looks like FreeType web server having issues tonight = problems with Harfbuzz ttfautohint dependency installation + build from source.  Repeat build passed without issues.

**Comment by burodepeper** [comment]
@chrissimpkins How do I clean up any remnants of the old build script to test whether this version installs all the correct dependencies etc?

**Comment by chrissimpkins** [comment]
fontmake and fonttools can be uninstalled with pip:

```
$ pip uninstall fontmake
$ pip uninstall fonttools
```

The Freetype library, Harfbuzz library, ttfautohint, sfnt2woff-zopfli, and woff2 are located in a directory on your $HOME path:

```
$ rm -rf ~/ttfautohint-build
$ rm -rf ~/sfnt2woff-zopfli-build
$ rm -rf ~/woff2
```

There is a temporary build directory that is written to root of the repository on path `master_ttf` that can hang around if the build process is disrupted (automated clean is at end) and this is cleaned up on the next build attempt.  Can remove it manually from root of Hack repo with:

```
$ rm -rf master_ttf
```

**Comment by chrissimpkins** [comment]
I probably should document all of the above in the BUILD.md documentation eh? :)

**Comment by chrissimpkins** [comment]
> Consider chaining it through, as this was what I expected and I did not see in the first place that it had been woff and woff2 complaining, since I had called build-subsets.sh.

Not following what you mean here by chaining it through.  Can you explain that?

**Comment by chrissimpkins** [comment]
https://github.com/source-foundry/Hack/pull/309/commits/73ee2b7410af8586ebbf00fd71d580e48124080c adds uninstall instructions to the BUILD.md build documentation.  Addresses David's question in https://github.com/source-foundry/Hack/pull/309#issuecomment-329408350

**Comment by chrissimpkins** [comment]
@jublo can you post the error message that you received and a bit more detail about https://github.com/source-foundry/Hack/pull/309#pullrequestreview-62899027 when you have a chance?  Added this to the TODO list for this PR but can't work on it at the moment because I don't understand the problem.

**Comment by chrissimpkins** [comment]
https://github.com/source-foundry/Hack/pull/309/commits/069656fa4bf98307e8f66a5112de936859a7aaa5 removes old web font build paths based upon discussion here https://github.com/source-foundry/Hack/issues/286#issuecomment-330005721

**Comment by chrissimpkins** [comment]
@jublo the `build-subscripts.sh` shell script indicates missing woff and woff2 build dependencies with the following tests and stdout/stderr messages:

```shell
# sfntwoff-zopfli installed
if ! [ -f "$SFNTWOFF_BIN" ]
	then
	    echo "sfnt2woff-zopfli was not found.  Please attempt to install this with ./build-woff.sh --install-dependencies, then execute this script again" 1>&2
	    INSTALLFLAG=1
else
	echo "sfnt2woff-zopfli executable identified"
fi

# woff2 installed
if ! [ -f "$WOFF2_BIN" ]
	then
	    echo "woff2 was not found.  Please attempt to install this with ./build-woff2.sh --install-dependencies, then execute this script again" 1>&2
	    INSTALLFLAG=1
else
	echo "woff2_compress executable identified"
fi
```

Can you let me know what you have in mind for the modification to address https://github.com/source-foundry/Hack/pull/309#pullrequestreview-62899027

**Comment by jublo** [comment]
@chrissimpkins Can you make `build-subsets.sh` accept optional parameter `--install-dependencies` that will call the sub scripts with the same parameter?

**Comment by chrissimpkins** [comment]
Must install all build dependencies across ttf + woff + woff2 builds to use subsetter script.  Best way to do this is to use the following command:

```
make build-with-dependencies
```

Afterwards you can use any of the individual build types.  The need to install these build dependencies before you use the `build-subsets.sh` script is documented in the header of the script if you intend to use it directly for builds:

```shell
 #  NOTE: must install build dependencies in:
#        1) build-ttf.sh
#        2) build-woff.sh
#        3) build-woff2.sh
#       before you execute this script.  You can do this with:
#
#
#       $ ./build-ttf.sh --install-dependencies
#       $ ./build-woff.sh --install-dependencies
#       $ ./build-woff2.sh --install-dependencies
```

**Comment by chrissimpkins** [comment]
The build documentation `docs/BUILD.md` that is part of this PR only indicates the make targets for builds.  Not currently suggesting use of the shell scripts directly.

**Comment by chrissimpkins** [comment]
@jublo perhaps we change the script stderr message to point to use of the make command rather than a direct use of the shell scripts for the dependency installs?  The dependency management is a headache and I would ideally like to just eliminate it and provide instructions, but I think that it is helpful to automate this process in a way that makes it simple for those who would otherwise not take the time to do it...

**Comment by jublo** [comment]
@chrissimpkins Good point, let's go for that.

**Comment by chrissimpkins** [comment]
@jublo added improvements to the stderr report to users on build dependency install fails across all build shell scripts in https://github.com/source-foundry/Hack/pull/309/commits/1c8e98d4e62ee1c666a35b71309dc966703e0a49 

Let me know if this addresses your concern so that we can merge this branch to `dev` branch.

**Comment by chrissimpkins** [comment]
@jublo thanks for the code review JM.  Really appreciate it!

**Comment by chrissimpkins** [comment]
Merged to `dev` branch

**Pull request merged**
