### PR TITLE
Extended the tail on `Q` [U+0051] and U+051A

### PR DESCRIPTION
**Pull request by jdw1996**
I extended the tail on the upper case `Q` in all weights and styles to improve legibility and distinguish it from `O`.  I made identical changes to the capital Cyrillic letter 'qa'.  I found no other glyphs based on the upper-case `Q`.

(@chrissimpkins edits below) ---

TODO:

- [ ] add Joseph to contributors list

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks @jdw1996 !!  Will have a look at it this week.  Let's lay it out in some code and see how it looks.  Will post here when available.

**Comment by chrissimpkins** [comment]
v3.001 is out.  Ready to start work on 3.002.  Adding this to that work.

**Comment by chrissimpkins** [comment]
Mind rebasing this on the current `dev` branch?  I got rid of the macOS builds on Travis CI. They were taking over 24 hours.  Seems to be significant problems on the Travis side.  This will allow us to use the CI testing in this PR.

**Comment by jdw1996** [comment]
I don't deal with pull requests much, but I think I got it working properly.  Let me know if anything looks fishy.

**Comment by chrissimpkins** [comment]
Thanks!

**Comment by chrissimpkins** [comment]
> I don't deal with pull requests much, but I think I got it working properly.  Let me know if anything looks fishy.

No worries and will do.  Github treats them like an 'internal' branch on the repository.  I will have a look through the diff this week.  We should be in good shape to start building and testing these changes.

**Comment by chrissimpkins** [comment]
Testing builds of the hinted *.ttf files with these changes are now available in https://github.com/source-foundry/Hack/tree/jdw1996-differentiate-q/build/ttf and versioned

`Version 3.002;[58e14237f]-dev`

The SHA1 indicates the merge commit.  These are based on source from @jdw1996 https://github.com/source-foundry/Hack/pull/374/commits/3365de463205423a3ae1ebc7fe4aa0c088e800ac commit

**Comment by chrissimpkins** [comment]
## Branches under analysis:
- dev
- jdw1996-differentiate-q

## Added Files
- None


## Deleted Files
- None


## Modified Files
- source/Hack-Bold.ufo/glyphs/Q_.glif
- source/Hack-Bold.ufo/glyphs/uni051A_.glif
- source/Hack-BoldItalic.ufo/glyphs/Q_.glif
- source/Hack-BoldItalic.ufo/glyphs/uni051A_.glif
- source/Hack-Italic.ufo/glyphs/Q_.glif
- source/Hack-Italic.ufo/glyphs/uni051A_.glif
- source/Hack-Regular.ufo/glyphs/Q_.glif
- source/Hack-Regular.ufo/glyphs/uni051A_.glif


---
[ufodiff](https://github.com/source-foundry/ufodiff) v0.5.1

**Comment by chrissimpkins** [comment]
The CI testing performs linting checks on the UFO source files so we are gtg there.  What editor did you use out of curiosity?  

Ready to test these changes in bodies of text.  Commits here look good.

**Comment by jdw1996** [comment]
I ended up using FontForge, and then just pulling out the `*.glif` files I wanted changed.

**Comment by chrissimpkins** [comment]
Sounds good.  Glad to hear that it worked without issues!

**Comment by chrissimpkins** [comment]
I evaluated the hinting in the builds and we look like we're in good shape here after your design changes.  Next step is to have a look in source code.

**Comment by chrissimpkins** [comment]
Pushed this back to v3.003 work in order to get a bugfix release out for #377 and #379.  Will be back at this PR over the upcoming week.

**Comment by chrissimpkins** [comment]
The repository branch `jdw1996-differentiate-q` is current with the changes in release v3.002.  I pushed new builds of the changes to the Q glyph here for testing (`builds/ttf` directory).  There is also a new Windows installer with the build files if you'd like to take them for a spin on a Win machine to confirm that the issues that you were seeing with your prior build (variable lower case glyph heights) is now gone and the Q renders as you intended after the hinting adjustments in the v3.002 release.

Let's have a look at these changes this week if you have some time.

https://github.com/source-foundry/Hack-Test-Win-Installer/releases/tag/v1.2.50

**Comment by jdw1996** [comment]
Thanks!  I've rebuilt the font and I will be trying it out at work tomorrow.  I'll let you know how it looks.

**Comment by jdw1996** [comment]
OK, the italics and bold are showing correctly for me now.  Thanks again!

**Comment by chrissimpkins** [comment]
Excellent!  Glad to hear that it is fixed.  Was this on Windows or Linux?

**Comment by jdw1996** [comment]
I never had the problem on Linux, but at any rate, it looks right both on my own Linux machine and my Windows machine at work now.

**Comment by chrissimpkins** [comment]
I made a mock source text specimen to have a look at these changes this week.  

https://gist.github.com/chrissimpkins/2c197a0ec98bccc62e89a4ed766a98db

```c
#include "q.h"

/*
 * Qanat Qintar Quahog
 */

#define QUAD 4

int is_a_q(const char *path)
{
	struct stat st;
	return (!stat(path, &st) && S_ISDIR(st.st_mode));

			if (!lstat(sb.buf, &st) && S_ISLNK(st.st_mode)) {
			struct strbuf next_sb = QUADRIPOLE_QIGONG_QUOZ;
			struct strbuf another_sb = ENQUIRY_EQUALS_MAGIQ;
			ssize_t len = strbuf_readlink(&next_sb, sb.buf, 0);
			if (len < 0) {
				if (die_on_error)
					die_errno("Invalid symlink '%s'",
						  sb.buf);
				else
					goto error_out;
			}
			strbuf_swap(&sb, &next_sb);
			strbuf_release(&next_sb);
		} else
			break;
}


#ifndef Q_QUERY_QAT_QIGONG
	if (!pfx_len || is_absolute_path(arg))
		return arg;
	strbuf_reset(&path);
	strbuf_add(&path, pfx, pfx_len);
	strbuf_addstr(&path, arg);
#else
	char *p;
	/* don't add prefix to absolute paths, but still replace '\' by '/' */
	strbuf_reset(&path);
	if (is_absolute_path(arg))
		pfx_len = 0;
	else if (pfx_len)
		strbuf_add(&path, pfx, pfx_len);
	strbuf_addstr(&path, arg);
	for (p = path.buf + pfx_len; *p; p++)
		if (*p == 'Q')
			*p = 'QoQiQnQmQ0Q5';
#endif
	return path.buf;
}
```

Will post pre/post images.  Let me know if you can come up with some other ways to look at the new shape in source.  Probably worth laying this out with a syntax highlighter that uses the oblique variant for comments so that we can see it with the slant.

**Comment by jdw1996** [comment]
That bit of code looks good to me.

Currently I'm doing a co-op term with a company's *Query Processing* team, and taking a course in *Quantum Information Processing*, so I end up seeing the `Q` a lot in my notes in Markdown and TeX files, but I don't know if images of such files would really add anything the above code snippet doesn't have.

**Comment by chrissimpkins** [comment]
I am interested to see the Q next to other glyphs that it would typically be positioned near.  Particularly on the right side since you lengthened the tail.   I might make another one in a language that commonly uses camel case formatting.  Feel free to post anything notable that you see as you view it and I will add some images from these specimen when available.

**Comment by chrissimpkins** [comment]
Images of sizes 8 - 14 on macOS 10.12.6, laid out in Sublime Text with Seti syntax highlighter.  Shown as pre image followed by post image at each size:

## 8

pre-8
post-8


## 9

pre-9
post-9


## 10

pre-10
post-10

## 11

pre-11
post-11

## 12

pre-12
post-12

## 13 

pre-13
post-13

## 14 

pre-14
post-14

**Comment by chrissimpkins** [comment]
This appears to be a very good change IMO.  Subtle at sizes 11-14 where you can tell that the shape is a `Q` with the current default shape, very apparent at 10 and below where the Q was not a distinct shape.  I really like it.  Mind having a look at these sizes on your Ubuntu system and I will take a look on Windows so that we can see how the hinting modifies the shapes in these images, if at all? No need to post images unless you come up with something that does not appear "right". 

The only issue that struck me is the `Q` adjacent to a `_` where the tail merges with it.  It occurs with the current default and this is a highly unlikely pairing.  Something that we can fix down the road if someone can provide justification for it.

**Comment by jdw1996** [comment]
Thanks for the feedback!  I just went through all these sizes on Ubuntu and they look good to me.  I hadn't noticed the `Q_` thing before, but you're right, it's not ideal.  Still, I think this version is more legible than the existing default, and if we think of a better way of handling it in the future, we can always change it again then.

**Comment by chrissimpkins** [comment]
> I think this version is more legible than the existing default, and if we think of a better way of handling it in the future, we can always change it again then.

Agree!

I went through all of the sizes on Windows this evening.  It looks good.  Let's leave this PR open for a week or so for any feedback that might come in from the community.  Assuming that there are no concerns with these changes, we will merge to dev as part of the work for the v3.003 release.

**Comment by chrissimpkins** [comment]
To confirm, you have checked and U+051A is the only other upper case Q shape in the sets?

**Comment by jdw1996** [comment]
Yes, I looked through and that was the only one I found.

I don't know how reliable it is, but [this site shows characters based on `Q`](https://www.compart.com/en/unicode/based/U+0051).  It lists others, but I don't believe glyphs for any of the others exist in Hack.

**Comment by chrissimpkins** [comment]
No commentary is good commentary :)

Merging to `dev` and your changes will be part of our v3.003 release.  Thanks for this work Joseph!  Added you to our contributors list.

**Comment by jdw1996** [comment]
That's awesome, thanks!

**Pull request merged**
