### PR TITLE
hint updates for ASCII regular, bold, italic, and bold italic sets

### PR DESCRIPTION
**Pull request by chrissimpkins**
Adds 

- manual changes to ttfautohinting instruction sets documented (including images) in #296, #297, #298, #299, #300, #301, #302, #303 
- update to Travis CI testing settings to address their change in Linux Trusty images (broke our CI testing and that of many others...) - commit https://github.com/source-foundry/Hack/commit/8f20b787e6efe96b1c1bd992bd58d7002887ccd9

Propose merge to `dev-build-scripts` branch followed by merge of `dev-build-scripts` to `dev` branch so that we can base remainder of outstanding v3.0 work (including PR's for v3.0) on that.   The work that I am able to do at this stage on build scripting and hinting is complete.  Happy to create a separate PR for the `dev-build-scripts` to `dev` merge once this is merged there if you'd like to review it.  `dev-build-scripts` includes all of the build scripting work for UFO>ttf, ttf>webfont, ttf>webfont subsets.  All of this is now ready for `dev` branch in anticipation of v3.0 release.

Let me know if you have any concerns about the new post-hinting adjustment shapes of the glyphs that were of concern here.

### CODE REVIEW

**Comment by burodepeper** [comment]
In #298, the vertical sections of the `+` in the 12px fixed version (see https://user-images.githubusercontent.com/4249591/30141161-90bc823a-9347-11e7-8ae3-ad8746c6473e.png) are larger than the horizontal sections. Could you make the vertical sections half a pixel shorter?

The rest looks good, at a quick glance!

**Comment by chrissimpkins** [comment]
> In #298, the vertical sections of the + in the 12px fixed version (see https://user-images.githubusercontent.com/4249591/30141161-90bc823a-9347-11e7-8ae3-ad8746c6473e.png) are larger than the horizontal sections. Could you make the vertical sections half a pixel shorter?

Absolutely!  Will make the change this evening and push new images in that IR thread.

**Comment by chrissimpkins** [comment]
@burodepeper Added suggested changes in https://github.com/source-foundry/Hack/commit/2a97b0d52ba4e34f1db8c5f56fc6b579595c6b05 and image of new shape in https://github.com/source-foundry/Hack/issues/298#issuecomment-328686755

**Comment by chrissimpkins** [comment]
👍 done!

**Pull request merged**
