### PR TITLE
Add glyph U+017F

### PR DESCRIPTION
**Pull request by jublo**
See #268, #324, #330.

### CODE REVIEW

**Comment by funkyfuture** [comment]
lgtm. huge thanks.

**Comment by chrissimpkins** [comment]
@funkyfuture able to link a sample block of text where we can have a look at this glyph in context?

**Comment by funkyfuture** [comment]
like [this](https://github.com/source-foundry/Hack/issues/268#issue-250381295)? or with the pending proposal?

**Comment by chrissimpkins** [comment]
@funkyfuture as I recall you were using this in historic texts.  Can you provide a couple of paragraphs of text so that we can view it once this glyph is in the sets?

**Comment by funkyfuture** [comment]
sure,

```
Ein Verzeichniß derſelben, nach natürlichen Familien geordnet,
mit kurzen charakteriſirenden Bemerkungen und genauer Angabe
des Standortes. Nebſt einer Beſchreibung des Friedrichshains und
geſchichtlichen und ſtatiſtiſchen Mittheilungen.

Wo dieſelben fehlen, war eine ſpecielle Charakteriſtik durch we-
nige Worte meiſtens nicht möglich, und durch eine größere Aus-
führlichkeit in der Beſchreibung, wie ich ſie gern gegeben, würde
der Preis des Werkes ſich gleich bedeutend erhöht haben. Daſſelbe
ſollte aber zu einem möglichſt billigen Preiſe abgegeben werden
können.

Wer jemals die Schwierigkeit kennen gelernt hat, eine gütliche
Bereinigung ſo Vieler zu einem gemeinſchaftlichen Schritte zu er-
wirken, der wird dieſelbe nicht für gering erachten, da der Wider-
ſtand oder Eigenſinn eines Einzelnen das ganze ſchöne Projekt
illuſoriſch machen konnte.
```

though i selected these randomly, the usual character sequences involving it are represented.

**Comment by chrissimpkins** [comment]
:+1:  thanks! will post images once the glyph is merged

**Comment by chrissimpkins** [comment]
Should be able to merge this into the sets this week and build a set that you can try in your historic texts @funkyfuture 

Bit of cleanup of dev branch source to prep for v3.001 work and then we will get started with this.

**Comment by chrissimpkins** [comment]
Merged into a working branch with a new set of font builds that include the glyph available here:

https://github.com/source-foundry/Hack/tree/jublonet-feature/glyph-017f/build/ttf

Here is a screenshot of your text specimen above that includes the new glyph designed by @jublo 

long_s

@funkyfuture Let us know what you think when you have a chance to view it locally.  If no further modifications are necessary, will merge to `dev` branch with plans to merge this as part of the next release (v3.001).

**Comment by chrissimpkins** [comment]
@jublo @funkyfuture does it need to be nudged to the right a bit in order to "pseudo-kern" vs. other glyphs that we are displaying it next to in the image above?  To my eye it seems a bit off center to the left but this is the first I have ever viewed this glyph in text so take that for what it is worth.

See line 4, character 3 (between the e and c) and line 16, character 17 (between the n and i) for examples.

**Comment by chrissimpkins** [comment]
poke

**Comment by funkyfuture** [comment]
peek.

sorry, quiet busy atm. but i have this on my overdue list. i may have an opportunity within the next hours.

**Comment by chrissimpkins** [comment]
No worries.  Let us know when you have a chance.  There is an image of your text specimen in https://github.com/source-foundry/Hack/pull/331#issuecomment-341610298 to demonstrate the appearance.

**Comment by chrissimpkins** [comment]
@funkyfuture 

> a) i'm not a nerd on typography

caveat understood :)

From my standpoint, wouldn't call it a concern at all.  If it looks ok in use to you, I am good with it.  We really needed someone who looks at the glyph and knows what it looks like in other faces to comment so you are without a doubt the use case specialist / expert here.  Your input is valuable.  

@jublo thoughts?  Leave as is and merge or modify further?

**Comment by jublo** [comment]
@funkyfuture This is moved over a bit. Still more?

grafik

**Comment by jublo** [comment]
@funkyfuture Moved it over a bit. Still more?

grafik

**Comment by funkyfuture** [comment]
It really is beautiful.

**Comment by chrissimpkins** [comment]
:+1:  thanks!

**Comment by chrissimpkins** [comment]
Nice work @jublo.  Will merge over to dev this weekend and build new fonts.

**Comment by chrissimpkins** [comment]
@funkyfuture New builds are available in https://github.com/source-foundry/Hack/tree/dev/build/ttf and versioned as  Version 3.001; b9574cb-dev if you want to install them for use with this new glyph.

**Pull request merged**
