### PR TITLE
Add glyph U+017f

### PR DESCRIPTION
**Pull request by jublo**
See #268

### CODE REVIEW

**Comment by jublo** [comment]
See #324

**Comment by jublo** [comment]
@chrissimpkins What about this one?

**Comment by jublo** [comment]
@chrissimpkins No wait, I need to fix Y alignment.

**Comment by chrissimpkins** [comment]
Did you and @funkyfuture settle on a design for this glyph?

**Comment by jublo** [comment]
@chrissimpkins I used his last mentioned approach.

**Comment by chrissimpkins** [comment]
Let's give him a bit of time to weigh in before we merge this one.  You have current images posted in that thread to show him the design that you want to merge in this PR?

**Comment by jublo** [comment]
@chrissimpkins Will do.

**Comment by chrissimpkins** [comment]
These glif file merges are simple based upon the initial experience with your other Latin Ext A PR's.  If we don't hear back from him in the next day or two, we will merge it and can modify down the road if there are any changes necessary.  Once the XML is added to the plist files (i.e. modifications of current glyphs), it becomes very simple.  There is nothing to do other than merge to the sets.

**Comment by chrissimpkins** [comment]
How has the .glif only workflow worked so far?  This problematic to limit PR to only .glif files?

**Comment by chrissimpkins** [comment]
Sorry didn't mean to close this.  `dev-latin-a` was a temporary branch.  Mind rebasing these changes on `dev`?

**Pull request closed without merging**
