### PR TITLE
Add glyphs U+012C..U+012D

### PR DESCRIPTION
**Pull request by jublo**
bildschirmfoto 2017-09-29 um 21 55 20
bildschirmfoto 2017-09-29 um 21 56 10
bildschirmfoto 2017-09-29 um 21 56 35
bildschirmfoto 2017-09-29 um 21 57 21

### CODE REVIEW

**Comment by jublo** [comment]
@chrissimpkins I did not touch the metadata – please advise if you’re going to do that on your own.

**Comment by chrissimpkins** [comment]
No problem JM, I can definitely take care of the metadata.  Thanks for adding these glyphs!

Associated issue report for missing glyphs in the Latin Ext A set: https://github.com/source-foundry/Hack/issues/324

**Comment by chrissimpkins** [comment]
@jublo out of interest, did you modify the design in a different repository or add the plist files to .gitignore?

**Comment by jublo** [comment]
@chrissimpkins I added the glyphs like always, and from the list of changed files, I discarded anything except those new files.

**Comment by jublo** [comment]
Fixed horizontal position of the breve on lowercase letter in Regular now.

**Comment by jublo** [comment]
Renamed files to their correct names.

**Comment by chrissimpkins** [comment]
> I discarded anything except those new files

Like this? Or did you manually revert the plist files that editor changed?

```
$ git add *.glif
$ git commit -m "message"
$ git push
```

Trying to come up with a PR workflow that is simple and does not modify the plist XML files

**Comment by jublo** [comment]
I took a look at the changed files in SmartGit, like this:

bildschirmfoto 2017-09-30 um 14 09 50

Then I would select anything except the glif file.

bildschirmfoto 2017-09-30 um 14 10 27

And finally commit the remaining file.

**Comment by chrissimpkins** [comment]
so you just work in a dirty repository with the plist modifications that happen with the edits and do not commit those?

**Comment by jublo** [comment]
@chrissimpkins That's right.

**Comment by chrissimpkins** [comment]
merged into `dev-latin-a` branch.  will merge to `dev` once we have tests passing.  Need the regular variant glyphs for ebreve / Ebreve before we can complete the build to confirm.

**Comment by chrissimpkins** [comment]
tests passed.  merged to `dev`

**Pull request merged**
