### PR TITLE
Add glyphs U+0114..U+0115 (Italic, Bold, BoldIt)

### PR DESCRIPTION
**Pull request by jublo**
bildschirmfoto 2017-09-30 um 13 33 24
bildschirmfoto 2017-09-30 um 13 38 20
bildschirmfoto 2017-09-30 um 13 39 38

See https://github.com/source-foundry/Hack/issues/324.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
ufolint works :)

https://travis-ci.org/source-foundry/Hack/jobs/282531542#L635

Seems that we don't have the ebreve and Ebreve glyphs (ebreve.glif and E_breve.glif) in the regular set.  Mind adding the regular set as well?

**Comment by jublo** [comment]
@chrissimpkins Hmm, this comment confused me:

> Latin Ext A:
> 
> U+0114...U+0115 (missing in italic, bold, bold italic)

**Comment by chrissimpkins** [comment]
No you were correct in your interpretation.  For some reason it was displayed when I reviewed the web font subsets, but I can confirm that there is .glif file for those in the regular set...

**Comment by chrissimpkins** [comment]
Thanks JM.  Let me merge these and see if it passes now

**Comment by chrissimpkins** [comment]
Here is where we are with build:  

https://travis-ci.org/source-foundry/Hack/builds/282535293

linting now passes.  build underway on Linux and OS X

**Comment by chrissimpkins** [comment]
tests passed with addition of the regular set glyphs.  merged to `dev`

**Pull request merged**
