### PR TITLE
Redrawing the zero (work in progress)

### PR DESCRIPTION
**Pull request by burodepeper**
As requested, I've started redrawing the `zero` glyph. My initial approach is to simply fill in the oval with a shape that's offset from the outer oval by the horizontal and vertical stroke-widths. It looks visually balanced, and there's a logic in the distances that should help the hinting of the shape. To achieve this, I've created two offset shapes (for both horizontal and vertical offsets) and manually merged these until I was content with the resulting shape.

I've attached a visual-diff of the shapes. Blue is before, red is after. This approach should work when hinted with a minimal horizontal resolution of 5px. At smaller sizes it looks a bit more _Eye of Sauron', but it should work better with hinting. With the bold variants, the biggest issue is the reduced space that is available. The same approach isn't possible, but by keeping the distances and size from the Regular variant, some of the boldness could be sacrificed to achieve a similar effect.

schermafbeelding 2017-08-22 om 12 32 56

### TODO

- [ ] Manually fix the coordinates of the original glyph (across variants) to regain horizontal and vertical symmetry.
- [ ] Test whether this approach doesn't fill up the outer oval (at smaller sizes) when hinted.
- [ ] Add inner ovals to Italic, Bold and Bold Italic variants.
- [ ] remove .gitignore changes and eliminate unnecessary directories and files in repository that resulted from previous failed build with dependency install (see https://github.com/source-foundry/Hack/pull/276#issuecomment-324022517)

PS, _obviously_ I based my local branch off of the wrong thing, but I'll figure that out later ;)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Looks great David!

> My initial approach is to simply fill in the oval with a shape that's offset from the outer oval by the horizontal and vertical stroke-widths. 

👍 

> At smaller sizes it looks a bit more _Eye of Sauron', but it should work better with hinting. 

Let me know when your design changes are complete and I will examine the hinting.  This is a glyph that required modification of our manual hinting and these changes are likely to modify the points that need to be used for these adjustments.  This *may* make the hinting job easier, hoping at least.  Will wait for you to reach a point where you are satisfied with your design changes before I dive in on the hints because further changes will modify anything that I do.  If you need this feedback prior to that time let me know and we can post images of changes in design and post hinted renders back and forth to reach a final design.

> The same approach isn't possible, but by keeping the distances and size from the Regular variant, some of the boldness could be sacrificed to achieve a similar effect.

Post images when you have them!. Your visual diff tool images work great to discuss these changes.

Also, if you haven't set up a development environment to build fonts that you can install and test, the build.sh script in the `dev-build-scripts` branch now works.  You can install build dependencies with:

```
$ ./build.sh --install-dependencies
```  

and then perform all future desktop ttf builds with:

```
$ ./build.sh
```

from root of repository.

**Comment by chrissimpkins** [comment]
For the file changes here:

- fontinfo.plist is an important file.  Glyphs appears to modify the version integer from 000 to 0.  This should not be an issue.  
- features.fea - I'm not quite sure what Glyphs is attempting to do in this file.  We need to add superscript features back into this file and can check it again when this is complete to confirm that it doesn't continue to make changes here.  There are some form of case swapping that occurs in some of the extended glyphs that I commented out with the source change.  Seems to be modifying this in some fashion.
- .gitignore - can I ask you to remove the changes here?  These seem to be related to the old build script that pulled dependency archives into your repository and created a temporary font build directory, then failed and didn't clean them up.  `master_ttf` and `ttfautohint-1.6` directories and the ttfautohint.tar.gz archive can all be removed from your repository.  I don't know what the config.log file is.
- lib.plist is an optional file in UFO source that is intended as an application specific data store.  These changes will not influence builds.  I *don't think* that it should influence a multi-editor workflow either.

**Comment by chrissimpkins** [comment]
> PS, obviously I based my local branch off of the wrong thing, but I'll figure that out later ;)

I think that you are ok.  You seem to be based on dev.  You can merge `dev-build-scripts` into your working branch here to pull in the build script if you want to work with build files.

**Comment by chrissimpkins** [comment]
As you work on .glif files, have a look at the .glif source for the design changes and see if you come up with any approach that might allow for us to "lint" design changes in any valuable way.  We have access to these data and can include this in the ufolint tests that are executed on all UFO source changes with every commit, including those here.

**Comment by chrissimpkins** [comment]
see https://github.com/source-foundry/Hack/issues/277 for a proposal to address the local lib.plist changes (metadata that are intended for editors, are editor specific and influenced by choice of editor by contributor).  I think this might be a good approach to eliminate this issue.  Contributors keep their lib.plist data local and do not push to the remote repo.

**Comment by chrissimpkins** [comment]
How are things coming with this David?

**Comment by burodepeper** [comment]
@chrissimpkins Haven't had time yet, too busy with personal issues.

**Comment by chrissimpkins** [comment]
No worries bud.  Look forward to seeing how they look when you have a chance to get back to it.

**Comment by chrissimpkins** [comment]
As we close in on v3 changes wrapping up let me know if this seems feasible to complete.   I am tackling the hints and can hint the old zero if you don't feel that this is something that we will be able to include as of v3 initial release.  If not we will definitely merge it whenever done down the road.  Will need to re hint the glyph when you are done.

**Comment by burodepeper** [comment]
@chrissimpkins Will do. Give me a week or so, then I'll know how feasible it is.

**Comment by chrissimpkins** [comment]
Sounds good.  We have a fair amount of work left yet.  Let me go through all of the open IR and I can let you know where things stand on my end as well.

**Comment by chrissimpkins** [comment]
This a branch/PR that you intend to get back to David?  Will be doing some repo cleanup (IR/PR) this week.  Let me know if we should close PR and how to manage branch in repo based upon plans with this zero glyph work.   Will need to be rebased on current dev branch when / if we move forward with this.

**Comment by burodepeper** [comment]
@chrissimpkins I was intending to yes, but I can 'easily' remake these, so feel free to remove the branch.

**Comment by chrissimpkins** [comment]
No worries about the branch.  If you intend to get back to it we can leave it there unless it is easier to just create a new one with all of the changes since you branched.  Will close PR until you are ready to commit changes.

**Pull request closed without merging**
