### PR TITLE
Add glyphs U+2024..U+2025

### PR DESCRIPTION
**Pull request by jublo**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks @jublo. Will get these merged this week.

**Comment by chrissimpkins** [comment]
Do you mind posting a screenshot of the new glyphs that you added in each of these three PR so that they are available for public review (and my own...)?

**Comment by jublo** [comment]
grafik Compare to grafik

grafik Compare to grafik

grafik Compare to grafik

grafik Compare to grafik

**Comment by chrissimpkins** [comment]
👍 👍 👍 ty!

**Comment by chrissimpkins** [comment]
@jublo merged!

**Pull request merged**
