### PR TITLE
Numeral one (U+0031) re-design to address legibility vs. lowercase l (U+006c)

### PR DESCRIPTION
**Pull request by chrissimpkins**
Modifications to the numeral 1 design to address legibility issues with the lowercase l (issue #43)

Includes the following changes to the glyph design in the `dev-one-design` branch:

- increased angle of top stroke relative to horizontal
- increased length of top stroke
- decreased width of the top stroke (bold and bold italic sets) - uses same dimensions as the left angled stroke in the numeral 4 in these sets

See images in #43 thread for the new design.

Please feel free to modify the working branch with design changes to address any concerns that you have.  We will include modifications in this PR for further discussion.

Build files for local testing are available in https://github.com/source-foundry/Hack/tree/dev-one-design/build/ttf and carry the version string `
Version 3.001; 379b3ad-dev`.

Propose merge to `dev` branch as new default U+0031 glyphs in the sets for release as of v3.001. 

When the design is acceptable, I will need to evaluate hinting at our design target range of 8 - 14ppem before merge.

TODO:

- [x] examine hints at 8 - 14 ppem regular set
- [x] examine hints at 8 - 14 ppem italic set
- [x] examine hints at 8 - 14 ppem bold set
- [x] examine hints at 8 - 14 ppem bold italic set

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@burodepeper if you can point me to your visual diff repo (with a brief set of instructions) I would be happy to link the design diff for these changes as well.

**Comment by burodepeper** [comment]
It looks awfully similar to U+2960...

**Comment by chrissimpkins** [comment]
= Upwards Harpoon with Barb Left from Bar

Assuming our users are not routinely placing harpoons in their code do you have other thoughts about the legibility issue against the glyph of concern.

**Comment by chrissimpkins** [comment]
hints look good across 8-14ppem x all four sets

**Pull request merged**
